[2023-09-15T15:27:08.652+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.branching scheduled__2023-09-14T00:00:00+00:00 [queued]>
[2023-09-15T15:27:08.682+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.branching scheduled__2023-09-14T00:00:00+00:00 [queued]>
[2023-09-15T15:27:08.684+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-09-15T15:27:08.717+0000] {taskinstance.py:1327} INFO - Executing <Task(BranchPythonOperator): branching> on 2023-09-14 00:00:00+00:00
[2023-09-15T15:27:08.729+0000] {standard_task_runner.py:57} INFO - Started process 182 to run task
[2023-09-15T15:27:08.737+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'eCommerce_ETL_dag', 'branching', 'scheduled__2023-09-14T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmp2s4qy0h1']
[2023-09-15T15:27:08.749+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask branching
[2023-09-15T15:27:08.877+0000] {task_command.py:410} INFO - Running <TaskInstance: eCommerce_ETL_dag.branching scheduled__2023-09-14T00:00:00+00:00 [running]> on host 228226a2581e
[2023-09-15T15:27:09.103+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='eCommerce_ETL_dag' AIRFLOW_CTX_TASK_ID='branching' AIRFLOW_CTX_EXECUTION_DATE='2023-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-14T00:00:00+00:00'
[2023-09-15T15:27:09.179+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 215, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/workflow.py", line 28, in check_table_count
    check = cursor.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
[2023-09-15T15:27:09.816+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=eCommerce_ETL_dag, task_id=branching, execution_date=20230914T000000, start_date=20230915T152708, end_date=20230915T152709
[2023-09-15T15:27:09.889+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task branching ('NoneType' object is not subscriptable; 182)
[2023-09-15T15:27:10.147+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-15T15:27:10.432+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-15T17:32:14.096+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.branching scheduled__2023-09-14T00:00:00+00:00 [queued]>
[2023-09-15T17:32:14.112+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.branching scheduled__2023-09-14T00:00:00+00:00 [queued]>
[2023-09-15T17:32:14.114+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-09-15T17:32:14.136+0000] {taskinstance.py:1327} INFO - Executing <Task(BranchPythonOperator): branching> on 2023-09-14 00:00:00+00:00
[2023-09-15T17:32:14.143+0000] {standard_task_runner.py:57} INFO - Started process 217 to run task
[2023-09-15T17:32:14.154+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'eCommerce_ETL_dag', 'branching', 'scheduled__2023-09-14T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmph_u614e1']
[2023-09-15T17:32:14.162+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask branching
[2023-09-15T17:32:14.266+0000] {task_command.py:410} INFO - Running <TaskInstance: eCommerce_ETL_dag.branching scheduled__2023-09-14T00:00:00+00:00 [running]> on host 1b1f4bc7eb40
[2023-09-15T17:32:14.391+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='eCommerce_ETL_dag' AIRFLOW_CTX_TASK_ID='branching' AIRFLOW_CTX_EXECUTION_DATE='2023-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-14T00:00:00+00:00'
[2023-09-15T17:32:14.408+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 215, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/workflow.py", line 21, in check_table_count
    cursor.execute("""
psycopg2.errors.UndefinedColumn: column "usersData" does not exist
LINE 5:                         WHERE table_name = "usersData"
                                                   ^

[2023-09-15T17:32:14.426+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=eCommerce_ETL_dag, task_id=branching, execution_date=20230914T000000, start_date=20230915T173214, end_date=20230915T173214
[2023-09-15T17:32:14.447+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task branching (column "usersData" does not exist
LINE 5:                         WHERE table_name = "usersData"
                                                   ^
; 217)
[2023-09-15T17:32:14.492+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-15T17:32:14.558+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
