[2023-09-15T16:17:10.456+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.predata_processing manual__2023-09-15T16:16:14.686512+00:00 [queued]>
[2023-09-15T16:17:10.471+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eCommerce_ETL_dag.predata_processing manual__2023-09-15T16:16:14.686512+00:00 [queued]>
[2023-09-15T16:17:10.473+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-09-15T16:17:10.493+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): predata_processing> on 2023-09-15 16:16:14.686512+00:00
[2023-09-15T16:17:10.499+0000] {standard_task_runner.py:57} INFO - Started process 1639 to run task
[2023-09-15T16:17:10.506+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'eCommerce_ETL_dag', 'predata_processing', 'manual__2023-09-15T16:16:14.686512+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmpbeep0f5h']
[2023-09-15T16:17:10.511+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask predata_processing
[2023-09-15T16:17:10.574+0000] {task_command.py:410} INFO - Running <TaskInstance: eCommerce_ETL_dag.predata_processing manual__2023-09-15T16:16:14.686512+00:00 [running]> on host 228226a2581e
[2023-09-15T16:17:10.675+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='eCommerce_ETL_dag' AIRFLOW_CTX_TASK_ID='predata_processing' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T16:16:14.686512+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T16:16:14.686512+00:00'
[2023-09-15T16:17:10.679+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-15T16:17:10.681+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /usr/local && spark-submit --master spark://spark-master:7077 ./PreDataProcessing-assembly-0.1.jar']
[2023-09-15T16:17:10.693+0000] {subprocess.py:86} INFO - Output:
[2023-09-15T16:17:10.709+0000] {subprocess.py:93} INFO - /usr/local/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-09-15T16:17:12.898+0000] {subprocess.py:93} INFO - WARNING: An illegal reflective access operation has occurred
[2023-09-15T16:17:12.900+0000] {subprocess.py:93} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/usr/local/spark/assembly/target/scala-2.12/jars/spark-unsafe_2.12-3.2.4.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2023-09-15T16:17:12.902+0000] {subprocess.py:93} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2023-09-15T16:17:12.903+0000] {subprocess.py:93} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2023-09-15T16:17:12.911+0000] {subprocess.py:93} INFO - WARNING: All illegal access operations will be denied in a future release
[2023-09-15T16:17:13.558+0000] {subprocess.py:93} INFO - 23/09/15 16:17:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-09-15T16:17:14.020+0000] {subprocess.py:93} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2023-09-15T16:17:33.026+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-09-15T16:17:33.487+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 1639. PIDs of all processes in the group: [1640, 1639]
[2023-09-15T16:17:33.983+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 1639
[2023-09-15T16:17:34.031+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-09-15T16:17:34.035+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-09-15T16:17:35.635+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-09-15T16:17:36.610+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=eCommerce_ETL_dag, task_id=predata_processing, execution_date=20230915T161614, start_date=20230915T161710, end_date=20230915T161736
[2023-09-15T16:17:37.766+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task predata_processing (Task received SIGTERM signal; 1639)
[2023-09-15T16:17:38.708+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1639, status='terminated', exitcode=1, started='16:17:10') (1639) terminated with exit code 1
